### ISSUE TITLE
插件加载错误

### ISSUE THREAD

**Issue by PackageInstaller** [lgc-NB2Dev/nonebot-plugin-rimofun#1]
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-rimofun/assets/80018096/0e150cb1-c9b4-4bd7-9b88-420912fa3fc6)
报错截图如上
OS：Arch linux
Bot：zhenxun_bot
python 版本：3.11.3
nonebot版本：2.0.0rc4
已执行过`pip install unvcode yinglish nonebot-plugin-rimofun`命令安装依赖，插件是git下来的

**Comment by lgc2333** [comment]
`git submodule update --init --recursive`

**Comment by PackageInstaller** [comment]
已解决
